### ISSUE TITLE
Update link to FlarmNet Database file

### ISSUE THREAD

**Issue by Symbian9** [XCSoar/website#12]
Link to FlarmNet Database on Download page is broken

- https://xcsoar.org/download/data.html
  - ~~http://www.flarmnet.org/files/data.fln~~

Actual link is:

- https://www.flarmnet.org/static/files/wfn/data.fln

### REFERENCE

- https://www.flarmnet.org/flarmnet/downloads/

**Comment by lordfolken** [comment]
Please also add references to OGN and the relevant database.

Also explain that these things can be downloaded via file manager. Refer to relevant sections in manual.

**Comment by rawtaz** [comment]
This issue can be closed.
