### ISSUE TITLE
6.8.12 news is missing

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/website#13]
We have released only on Playstore, but not on any other platform. 

See: 
https://github.com/XCSoar/XCSoar/issues/223

**Comment by Exadios** [comment]
I'm presently running XCSoar v6.8.12.2.1 on my Kobo. This is our club's current latest version. It is based (that is, rebased) on the upstream v6.8.12. So, I can supply a v6.8.12 binary for the Kobo. I can also supply a UNIX binary. I don't know if that's the help you want.

**Comment by lordfolken** [comment]
Closing this as this is a non-issue.
