### ISSUE TITLE
Hardware: which (recent) smartphones to recommend?

### ISSUE THREAD

**Issue by mlep** [XCSoar/website#21]
Currently, the page https://www.xcsoar.org/hardware/ recommends old smartphones.
Which recent smartphones to recommend?
Please provide a list to be added to the hardware webpage.

**Comment by lordfolken** [comment]
Yes this information is very outdated. I'd refrain from adding specific hardware for android. The phones are changing every 6 months or so. Here i would suggest refrain from mentioning a specific android phone and post more the android versions that are supported.

We should also mention openvario. And possibly the commercial solution from https://stefly.aero or rbe-avionik.de. 

The Peripherial list should be updated. LXNAV is now on S8/S100. 

We need to mention that the trivadis device is EOL as its based on windows ce.
