### ISSUE TITLE
Forums are down, and I'm not sure where to go to ask questions

### ISSUE THREAD

**Issue by austinjames314** [XCSoar/website#3]
The forums address is completely dead. Not sure how long for, but it's been days now for me. I have several questions about the operation of XCSoar, but I don't where I should go.

**Comment by lordfolken** [comment]
Didn't see this. Forums are up again. We are generally reachable over the following channels:

https://www.xcsoar.org/contact/

For the chat: Don't expect an immediate answer. Wait a couple of hours.
