### ISSUE TITLE
website hosting

### ISSUE THREAD

**Issue by codexx666** [XCSoar/website#32]
Hi,

we need to clarify some details regarding the hosting for the XCSoar website.

In a quick action we relocated the XCSoar website to an AWS EC2 instance to avoid a longer downtime.
Since beginning of May we switched to this (temporary) hosting solution.

The EC2 instance is doing 'fine' at the moment, but it generates way to much costs. Approx 60-80$ / month. 

So... I strongly advise that we find a different solution here.
If anybody can provide a long term hosting solution - great!

Otherwise I suggest that we move to a new rented hosting solution, for example with the german hosting provider Hetzner. My experience with Hetzner was quite ok so far over the last 10 years.
So I suggest we could get a hosting solution there.

- To relocate we need a guide / documentation what needs to be setup / configured.
- we should define some requirements
- we need to assign some responsibilities (who can manage the DNS entries, ...)

- long term: how can we "fund" the hosting? it's not that much, but it sums up over the month & years

I've tried to contact Max Kellermann and Folken a few times via EMail, but so far no response. :-/

**Comment by Ukrainec** [comment]
Why do you want to move to another hosting? I can not understand the reason for the move. But if you are determined to change your hosting, I advise you to choose several providers, take a free trial period and compare their work. Based on statistics, you can choose the best option. At first, I advise you to connect monitoring of the site. After the transfer of the site, everything does not always work properly.

**Comment by kerel-fs** [comment]
Hi @codexx666,

> To relocate we need a guide / documentation what needs to be setup / configured.

Several services on the current hosting are already under configuration management (ansible), so this guide can be just a short README in this repo (non-public currently).

another point: Secrets sharing among all parties isn't solved yet (ie various CI access tokens etc).

I wounder if we should organize a meeting/call (mumble / nextcloud talk or similar) to discuss this topic?

Sincerely,
kerel / Fabian P. Schmidt

PS: Ok if I delete the obvious ad-SPAM post above me?

**Comment by codexx666** [comment]
Hi !

Folken and Max replied meanwhile. 

it seems that we are all quite busy at the moment, so my suggestion that we pick up that issue end of January / Februar next year. 
I'll keep the AWS T2 instance running as long as we need it.

But as I stated above - it was the quickest setup we could do around May, but it's also far from "cheap". So I want to relocate in the next months.

You bringing some up a good points we need to clarify and define.

I think a online meeting would be best. I could setup for example a MS Teams meeting or we use something like mumble, nextcloud or whatever ;-)

Let's get to that in January and find a date which works for all involved people. Ok?

Regards
flip / Philipp Nierkamp

ps: yes... strange posting. probably f***** spam

**Comment by lordfolken** [comment]
80/Monthly $ is a lot for what we have. 

We currently use:
 - 100GB Disk we currently use 34GB
 - 2*2400Mhz i5s (2nd gen)
 - 4GB Ram. 

we currently run: 
- download.xcsoar.org
- forum.xcsoar.org
- www.xcsoar.org
- bugs.xcsoar.org (the old trac, currently unconfigured)

In 231 days we did about 1.6TB of traffic

**Comment by codexx666** [comment]
Hi guys,

I just want to raise that topic again.

How do we want to proceed?

How about having a (virtual)meeting/call this month?
I could setup a MS Teams conference call and send an invitation link for that.
Posting it here is probably not a good idea ;-)

If something else would be better, than please propose it here.


topics
- _future hosting and financing it..._
- _"Secrets sharing among all parties isn't solved yet (ie various CI access tokens etc)."_
- future requirements
- managing the xcsoar DNS entries
- ...

How about a doodle for finding a date that works for everyone involved?
(BTW: who should be involved???)

regards
flip

**Comment by codexx666** [comment]
Hi there,

due to COVID-19 I had some free time today picked up on the XCSoar hosting issue.
Hope everbody is well!

Regarding the server
Currently we are running on an AWS instance and that's fine for now, but way too expensive for longterm.
At least I'm not going to sponsor it indefinitely ;-)

I've checked today a few hosting providers and the offers for dedicated and virtual root servers.
Personally I would prefer a dedicated root server over an virtual instance - even with assigned performance levels. From my professional experience virtual hosts are usually filled up right to the top and that has an effect on the performance. 
Dedicated root server means our own hardware and no concurrent usage on the system.

As I see it, we don't really need a huge or high performance system. 
But we probably don't want to upgrade again soon, so let's put in some reserve for the future.

The market is quite big and a lot of providers offer dedicated hardware root servers.
For a reasonable dedicated root server it's around 50EUR/month or more.

I'm running other servers at Hetzner and have had so far only good experiences with them.
Their offer for a small server is around 46EUR/month.
They also have a "used" server shop - there we good get decent hardware for 30EUR/month.

I would make the suggestion to pick one of those used servers for around 30EUR.


What do you think?
Other suggestions? Suggestion for other good providers?

Who can do the migration of the website?
Is it only you @lordfolken at the moment?
 @kerel-fs can you support the migration too?

looking forward for your input and thoughts...


regards
flip

**Comment by codexx666** [comment]
Addition

Maybe we can have a virtual meeting to discuss details?
How about Discord? I could easily setup a (permanent) server/channel related to the hosting discussions.
But I'm also fine with other solutions like Teams, Skype, ...

**Comment by lordfolken** [comment]
Check your aws contract. If one commits long term to a vm you save up to 80% on the costs. its really the flexible volume that you pay for. https://aws.amazon.com/savingsplans/ 

Hetzner is nice, but its the one we moved away from because they depreacted the server hardware.

**Comment by codexx666** [comment]
Hi,

yes I checked that.
we currently a t2.medium instance.
paying upfront for 1 year reduces the amount by 34% compared to on demand.
paying upfront 3 years means saving 55%

that's definitely an improvement, but it's still more expensive than other solutions.

> Hetzner is nice, but its the one we moved away from because they depreacted the server hardware.

Hmm... was XCSoar running in a virtual / hosted environment? 
As far as I know, Hetzner won't deprecate the hardware if it's a dedicated server. At least not for a long time. 

Again:
How about having a skype / discord or whatever call at some point to discuss on how to proceed from here. kerel-fs also suggested that...

**Comment by lordfolken** [comment]
Ok i created a discord server: https://discord.gg/ygJdhE @kerel-fs

**Comment by lordfolken** [comment]
We have again moved server, this year. Now at a nice hetzner instance.
