### ISSUE TITLE
Bugtraker move to github?

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/website#9]
Should we continue to use the old bugtraker, or instead move it to github?

**Comment by lordfolken** [comment]
https://bugs.xcsoar.org/ should redirect to the github bugtraker.

old bugs should be imported to github:
migrate Trac to GitHub Issues:  https://stackoverflow.com/a/6685996

**Comment by r0w4n** [comment]
Hasn't this been resolved now? Don't all bug links lead to github?

**Comment by lordfolken** [comment]
The old bugs should be importet to github point is not done. The question is whether we should.

**Comment by r0w4n** [comment]
Personally I'd start with a clean slate. If they still exist and are important they'll be submitted by someone into github.

**Comment by lordfolken** [comment]
agreed. /close
